site_name: Awesome static
theme:
  name: material
nav:
    - Home: index.md
    - CSS: css.md
    - Fonts: fonts.md
    - Game Assets: game-assets.md
    - Patterns: patterns.md
    - Photos: photos.md
    - Placeholders: placeholders.md
    - Icons: icons.md
    - Images: images.md
    - Sound and Music: music.md
    - Vector Illustrations: illustrations.md
