site_name: Awesome static
theme:
  name: material
nav:

    - CSS: css.md
    - Diagrams from text: diagrams-from-text.md
    - Fonts: fonts.md
    - Game Assets: game-assets.md
    - Icons: icons.md
    - Images Banks: images.md
    - Music and Sound: music.md
    - Patterns: patterns.md
    - Photos: photos.md
    - Placeholders: placeholders.md
    - Vector Ilustrations: illustrations.md
